import type { MigrationBuilder, ColumnDefinitions } from 'node-pg-migrate';

export const shorthands: ColumnDefinitions | undefined = undefined;

/**
 * The transactional outbox: domain events written by the same transaction that
 * writes the row they describe.
 *
 * The gap it closes is the two-write problem. `POST /v1/users` committed a row
 * and *then* published `user.created` in-process, so a crash in between left a
 * user nothing downstream ever heard about — and no amount of retrying the
 * publish helps, because the process that was going to retry is the one that
 * died. There are only two ways out: make the event part of the write, or make
 * the write part of the event. This table is the first.
 *
 * A row here is an *intent to deliver*, not a log. The relay deletes it on
 * success — see `outbox.store.ts` — so the table's steady-state size is the
 * backlog, not the traffic. That is a deliberate departure from
 * `idempotency_keys`, which retains rows because a client may retry against
 * them; nobody ever reads a delivered outbox row, and keeping it would need a
 * second janitor to stop it growing forever, which is exactly the defect PR #33
 * found in the idempotency table.
 */
export function up(pgm: MigrationBuilder): void {
  pgm.createTable('outbox_messages', {
    /**
     * Generated by the application, not by the database, and it becomes the
     * `DomainEvent.id` the subscriber sees. Delivery is at-least-once, so the
     * one thing a consumer needs in order to recognise a duplicate is an id
     * that survives redelivery — a `gen_random_uuid()` default would be stable
     * too, but only after a round trip, and the enqueuing transaction is the
     * one place that can hand the id back to its caller for free.
     */
    id: { type: 'uuid', primaryKey: true },
    /**
     * The claim order, and the only monotonic column here.
     *
     * What it does *not* provide is commit order: a sequence value is assigned
     * at INSERT, so a transaction that took its number first can still commit
     * second, and a relay polling for visible rows sees the later number first.
     * Ordering by it is therefore a cheap, stable tiebreak that keeps a backlog
     * draining roughly FIFO — not a guarantee any consumer may rely on. Ordered
     * per-aggregate delivery needs a partition key and one in-flight message
     * per key, which is a broker's job and deliberately not this table's.
     */
    seq: { type: 'bigserial', notNull: true },
    event_name: { type: 'text', notNull: true },
    /**
     * `jsonb` rather than `json`: the relay never round-trips the original text
     * and binary storage is what makes an operator's `WHERE payload->>'userId'`
     * usable on a backlog.
     */
    payload: { type: 'jsonb', notNull: true },
    /** The publishing request's `x-correlation-id`, when it had one. */
    correlation_id: { type: 'text' },
    /**
     * `now()` is `transaction_timestamp()`, so every message enqueued by one
     * transaction shares this value — which is correct, because they describe
     * the same commit. It is the time the fact happened, not the time the relay
     * got round to it.
     */
    occurred_at: { type: 'timestamptz', notNull: true, default: pgm.func('NOW()') },
    status: { type: 'text', notNull: true, default: 'pending' },
    /** Deliveries already attempted. `0` until the relay has tried once. */
    attempts: { type: 'integer', notNull: true, default: 0 },
    /**
     * The earliest a relay may claim this row. Advanced by the backoff ladder
     * after each failure, which is what keeps a broken dispatcher from being
     * hammered at poll frequency — and what keeps one poison message from
     * monopolising every batch.
     */
    available_at: { type: 'timestamptz', notNull: true, default: pgm.func('NOW()') },
    /** Truncated failure text from the most recent attempt. */
    last_error: { type: 'text' },
  });

  // Two states, not three. There is no `published`, because a delivered row is
  // deleted; a row that exists is either owed to somebody or has given up.
  pgm.addConstraint('outbox_messages', 'outbox_messages_status_check', {
    check: "status IN ('pending', 'dead')",
  });

  pgm.addConstraint('outbox_messages', 'outbox_messages_attempts_check', {
    check: 'attempts >= 0',
  });

  // A dead-lettered row exists to be read by a human, and the first question is
  // always why. The constraint is what keeps `status = 'dead'` from being
  // reachable without an answer — through the store, and through psql alike.
  pgm.addConstraint('outbox_messages', 'outbox_messages_dead_has_reason', {
    check: "status <> 'dead' OR last_error IS NOT NULL",
  });

  // The claim's index, and it is partial on purpose: the scan is always
  // `status = 'pending' AND available_at <= now()` ordered by the same columns,
  // so dead rows — the ones that accumulate — are not merely filtered out of
  // the result, they are absent from the index the relay walks.
  pgm.createIndex('outbox_messages', ['available_at', 'seq'], {
    name: 'outbox_messages_pending_idx',
    where: "status = 'pending'",
  });
}

export function down(pgm: MigrationBuilder): void {
  pgm.dropTable('outbox_messages');
}
